---
- hosts: all
  become: yes
  vars:
    download_version: 4.4.5
    nagios_code_location: /tmp
    ubuntu_packages:
      - autoconf
      - gcc
      - libc6
      - make
      - wget
      - unzip
      - apache2
      - php
      - libapache2-mod-php7.0
      - libgd2-xpm-dev
    make_package_list:
      - ./configure --with-httpd-conf=/etc/apache2/sites-enabled
      - make all
      - make install-groups-users
      - usermod -a -G nagios www-data
      - make install
      - make install-daemoninit
      - make install-commandmode
      - make install-config
      - make install-webconf
      - a2enmod rewrite
      - a2enmod cgi
      - ufw allow Apache
      - ufw reload
      - htpasswd -c /usr/local/nagios/etc/htpasswd.users nagiosadmin
  tasks:
  - name: failing installation non ubuntu server
    fail:
      msg: This installiont only work for ubuntu
    when: ansible_os_family == " debian "
  - name: installing packeges on ubuntu
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    loop: "{{ ubuntu_packages }}"
  - name: downloading file from gib hub
    get_url:
      url: "https://github.com/NagiosEnterprises/nagioscore/archive/nagios-{{ download_version }}.tar.gz"
      dest: "{{ nagios_code_location }}"
  - name: extracting downloaded file
    unarchive:
      src: "{{ nagios_code_location }}/nagioscore-nagios-4.4.5.tar.gz"
      dest: "/tmp/"
      remote_src: yes
  - name: installing binaries-deamon-apache-creatingnagiouser
    shell:
      cmd: "sudo {{ item }}"
    args:
      chdir: "/tmp/nagioscore-nagios-{{ download_version }}/"
    loop: "{{ make_package_list }}"
	notify:
      - restarting apache server
      - starting nagios
  handlers:
  - name: restarting apache server
    service:
      name: apache2
      enabled: yes
      state: restarted
  - name: starting nagios
    service:
      name: nagios
      state: started
